#!/bin/sh

BASE_INSTANCE=$1
TEST_SPEC_PATH=$2

if [ "$ALL_VERSIONS" != "" ]; then
    ./stellar-core -ll fatal --test -f $TEST_SPEC_PATH --base-instance $BASE_INSTANCE --all-versions -a -r simple 2> /dev/null
else
    ./stellar-core -ll fatal --test -f $TEST_SPEC_PATH --base-instance $BASE_INSTANCE -a -r simple 2> /dev/null
fi
