#!/bin/bash

# Copyright 2018 Stellar Development Foundation and contributors. Licensed
# under the Apache License, Version 2.0. See the COPYING file at the root
# of this distribution or at http://www.apache.org/licenses/LICENSE-2.0

BASE_INSTANCE="$1"
TESTS="$2"
: ${SELFTEST_LOG_LEVEL:="fatal"}

if [[ "$ALL_VERSIONS" != "" ]]; then
    ./stellar-core test --ll $SELFTEST_LOG_LEVEL --base-instance $BASE_INSTANCE --all-versions -w NoTests -a -r simple "$TESTS" 2> /dev/null
else
    ./stellar-core test --ll $SELFTEST_LOG_LEVEL --base-instance $BASE_INSTANCE -w NoTests -a -r simple "$TESTS" 2> /dev/null
fi
