#!/bin/sh

# Written by David Mazieres & Graydon Hoare 2013-2016.  Public domain.

countwords() {
    echo $#
}

PGDIRS=$(exec 2>/dev/null; cd /usr/lib/postgresql && ls -1d */bin | sort -rn)

findpg() {
    local cmd="$1"
    command -v "$cmd" > /dev/null && return
    for dir in /usr/bin /usr/local/bin $PGDIRS; do
	if text -x "$dir/$cmd"; then
	   PATH="${PATH}:$dir"
	   return
	fi
    done
    return 1
}

findpg psql
PSQL=psql

findpg pg_ctl
PGCTL=pg_ctl

cleanup() {
    $PGCTL stop -m immediate
    rm -rf "$PGDATA"
    exit
}

# Creates a temporary postgres database cluster, runs a command (or a
# shell), then deletes the database cluster.  If PGDATA is already
# set, then simply executes a command without running another postgres
# instance.
runpg() {
    export PGDATA=$(mktemp -d ${TMPDIR-/tmp}/pgtmp.XXXXXXXX)
    export PGHOST="$PGDATA"
    export PGUSER=postgres
    #export PGDATABASE=postgres

    trap cleanup 0 2 15

    echo Creating temporary PostgreSQL database cluster in "$PGDATA"

    $PGCTL init -s -o "--no-locale -U ${PGUSER-postgres} -A trust" \
	|| return 1
    conf="$PGDATA/postgresql.conf"
    usd=$(sed -ne '/#\(unix_socket_director[^ ]*\) =.*/{
                    s//\1/p
                    q
                   }' "$conf")
    cat >> "$conf" <<EOF
$usd = '$PGDATA'
listen_addresses = ''
logging_collector = yes
fsync = no
synchronous_commit = off
full_page_writes = off
EOF
    $PGCTL start -w -s
}

setup_test() {
    runpg || return 1
    for i in $(seq 0 15) ''; do
	$PSQL -c "create database test$i;"
    done
}

if test "$#" = 0; then
    if $PSQL -c '\quit' test 2> /dev/null || setup_test; then
	echo "Enabling PostgreSQL in most tests"
    else
	echo "Disabling PostgreSQL in most tests"
	export STELLAR_FORCE_SQLITE=1
    fi
    if [ "$ALL_VERSIONS" != "" ]; then
        ./stellar-core -ll fatal --test --all-versions -a -r simple
    else
        ./stellar-core -ll fatal --test -a -r simple
    fi
else
    # You can run "./test-pg bash" to get a shell with postgreSQL set up
    setup_test
    "$@"
fi
