#!/bin/sh

# Written by David Mazieres 2013-2015.  Public domain.

countwords() {
    echo $#
}

findcmd() {
    SEEK=$1
    CHECKDIRS="/usr/local/bin /usr/lib/postgresql"
    FOUND=$(2>/dev/null find $CHECKDIRS -name $SEEK)
    if [ -z "FOUND" ]
    then
        >&2 echo "Could not find $SEEK in any of $CHECKDIRS"
        exit 1
    elif [ $(countwords $FOUND) -ne 1 ]
    then
        >&2 echo "Multiple options for $SEEK found in $CHECKDIRS"
    fi
    echo $FOUND
}

: ${PGCTL:=$(findcmd pg_ctl)}
: ${PSQL:=$(findcmd psql)}

cleanup() {
    $PGCTL stop -m immediate
    rm -rf "$PGDATA"
    exit
}

# Creates a temporary postgres database cluster, runs a command (or a
# shell), then deletes the database cluster.  If PGDATA is already
# set, then simply executes a command without running another postgres
# instance.
runpg() {
    export PGDATA=$(mktemp -d ${TMPDIR-/tmp}/pgtmp.XXXXXXXX)
    export PGHOST="$PGDATA"
    export PGUSER=postgres
    #export PGDATABASE=postgres

    trap cleanup 0 2 15

    echo Creating temporary PostgreSQL database cluster in "$PGDATA"

    $PGCTL init -s -o "--no-locale -U ${PGUSER-postgres} -A trust" \
	|| return 1
    conf="$PGDATA/postgresql.conf"
    usd=$(sed -ne '/#\(unix_socket_director[^ ]*\) =.*/{
                    s//\1/p
                    q
                   }' "$conf")
    cat >> "$conf" <<EOF
$usd = '$PGDATA'
listen_addresses = ''
logging_collector = yes
fsync = no
synchronous_commit = off
full_page_writes = off
EOF
    $PGCTL start -w -s
}

setup_test() {
    runpg || return 1
    for i in $(seq 0 15) ''; do
	$PSQL -c "create database test$i;"
    done
}

if test "$#" = 0; then
    if $PSQL -c '\quit' test 2> /dev/null || setup_test; then
	echo "Enabling PostgreSQL in most tests"
    else
	echo "Disabling PostgreSQL in most tests"
	export STELLAR_FORCE_SQLITE=1
    fi
    ./stellar-core --test -a
else
    # You can run "./test-pg bash" to get a shell with postgreSQL set up
    setup_test
    "$@"
fi

