#!/bin/bash

# Copyright 2018 Stellar Development Foundation and contributors. Licensed
# under the Apache License, Version 2.0. See the COPYING file at the root
# of this distribution or at http://www.apache.org/licenses/LICENSE-2.0

"${top_srcdir}/src/test/selftest-parallel" "${top_srcdir}/src/test/run-selftest-nopg" \
    && exec "${top_srcdir}/src/test/check-sorobans"
