# Build stage, includes everything needed to build.
FROM ubuntu:focal as buildstage
ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get update && \
    apt-get -y install iproute2 procps lsb-release \
                       git build-essential pkg-config autoconf automake libtool \
                       bison flex libpq-dev parallel libunwind-dev \
                       clang-10 libc++abi-10-dev libc++-10-dev \
                       postgresql

COPY . stellar-core/
WORKDIR stellar-core
RUN git clean -dxf
RUN git submodule foreach --recursive git clean -dxf

ARG CC=clang-10
ARG CXX=clang++-10
ARG CFLAGS='-O3 -g1 -fno-omit-frame-pointer'
ARG CXXFLAGS='-O3 -g1 -fno-omit-frame-pointer -stdlib=libc++'

RUN ./autogen.sh
RUN ./configure CC="${CC}" CXX="${CXX}" CFLAGS="${CFLAGS}" CXXFLAGS="${CXXFLAGS}"
RUN sh -c 'make -j $(nproc)'
RUN make install

# Deploy stage, only includes stuff needed to run.
FROM ubuntu:focal
ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get update && \
    apt-get -y install libunwind8 postgresql curl sqlite iproute2 libc++abi1-8 libc++1-8

COPY --from=buildstage /usr/local/bin/stellar-core /usr/local/bin/stellar-core
EXPOSE 11625
EXPOSE 11626
CMD stellar-core
