name: Horizon Integration Tests

on:
  pull_request:
  push:
    branches:
      - master

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  horizon:
    uses: stellar/stellar-horizon/.github/workflows/integration-tests.yml@c9e78ebefea9721fcb0b386fc898e4c0e76cee33
    with:
      horizon_git_ref: protocol-next
      core_git_ref: ${{ github.sha }}
      protocol_version: '27'
      stellar_rpc_docker_img: 'stellar/stellar-rpc:27.1.1'
