name: RPC Integration Tests

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  rpc-integration:
    uses: stellar/stellar-rpc/.github/workflows/stellar-rpc.yml@main
    with:
      core_git_ref: ${{ github.sha }}
