name: RPC Integration Tests

on:
  pull_request:
  push:
    branches:
      - master

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  rpc:
    uses: stellar/stellar-rpc/.github/workflows/integration-tests.yml@efd9eb95f1ed8a7d69d28f12e89762c3ecb64bcc
    with:
      rpc_git_ref: protocol-next
      core_git_ref: ${{ github.sha }}
      protocol_version: '27'
