name: RPC Integration Tests

on:
  pull_request:
  push:
    branches:
      - master

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  rpc:
    name: RPC integration tests
    uses: stellar/stellar-rpc/.github/workflows/integration-tests.yml@main
    with:
      core_git_ref: ${{ github.sha }}
      protocol_version: '25'
